[tool.semantic_release]
tag_format = "v{version}"
commit_parser = "conventional"
version_variables = ["VERSION:*:nf"]

[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.semantic_release.changelog]
template_dir = "templates"

[tool.semantic_release.publish]
upload_to_vcs_release = true
